# Generated by Django 5.2.1 on 2025-05-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced scraping options including formats, proxy settings, extraction schema, map options, search parameters, and AI agent configuration for intelligent navigation', null=True),
        ),
    ]
